### ISSUE TITLE
Different pressure limits for front and rear tyres?

### ISSUE THREAD

**Issue by boodysaspie** [VincentMasselis/TPMS-advanced#24]
**Is your feature request related to a problem? Please describe.**
I bought a third party TPMS system from A****press but I can't find an Android app (Atoto head unit) which lets me set different pressure warning levels for front vs rear tyres.

**Describe the solution you'd like**
An option to set warning levels for both front and rear axles (in my case, 2.2 front and 2.0 rear).

**Describe alternatives you've considered**
I'm not a programmer, so I've only tried pre-existing apps from the Play Store.

**Additional context**
I don't have much information about the system, except they are Bluetooth, transmitting on a frequency of 433.92MHz. The stock Atoto TPMS app recognises them, but I can only set one pressure limit. 

Here is the kit I bought:

https://www.aliexpress.com/item/1005005611418662.html

**Comment by VincentMasselis** [comment]
Hello

I also bought one of this sensors recently, thoses with the 2 letters on the sticker. Theses are different from the current supported sensors, I'm working to handle them ;)

**Comment by VincentMasselis** [comment]
Hey !
I just pushed a release which include a support for the Pecham sensors into the beta channel of the Play Store. If you want to try this new version, follow [this link](https://play.google.com/apps/testing/com.masselis.tpmsadvanced) to become a beta tester.

**Comment by 2solt** [comment]
Hi, I think this issue is still valid  based on the title.
For motorcycles spesificly would be nice to set different preasure ranges for the front and the back tyres
